name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 1) website/ klasörüne girip bağımlılıkları kur
      - name: Install website dependencies
        run: npm ci
        working-directory: ./website

      # 2) Docusaurus sitesini build et
      - name: Build website
        run: npm run build
        working-directory: ./website

      # 3) Elde edilen siteyi gh-pages dalına deploy et
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./website/build
